version: 2
updates:
  - package-ecosystem: npm
    directory: /
    schedule:
      interval: weekly
      day: monday
    groups:
      all-dependencies:
        patterns: ["*"]
    target-branch: github-working-app-2026-06-16

  - package-ecosystem: github-actions
    directory: /
    schedule:
      interval: weekly
      day: monday
    target-branch: github-working-app-2026-06-16
